# Containers used for this application
services:
  # Apache/PHP service
  apache-php:
    container_name: apache-php
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_PASSWORD=QTzp47dI5GoNqPzl
    ports:
      - "1337:80"
    networks:
      - olympians-network

  # Database service
  mariadb:
    container_name: mariadb
    image: mariadb:10.9
    environment:
      - MARIADB_ROOT_PASSWORD=QTzp47dI5GoNqPzl
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=t3l0s
    networks:
      - olympians-network

# Docker networks
networks:
  olympians-network:
    driver: bridge
