[meta]
id = "coordinates"
category = "forensics"
difficulty = "easy"
name = "Coordinates"
description = """
> by Spaghetti
There is a flag hidden somewhere in this file.

[flag]({{ linkify.static("flag") }})
"""
tags = ["Forensics", "Hardware", "Misc"]


[scoring]
flag = "clubeh{c0mpu73r_num3r1c41_c0n7r01_4fmC5sJz}"

