[meta]
id = "coordinates"
category = "forensics"
difficulty = "medium"
name = "Coordinates"
description = """
> by Spaghetti

We discovered a t3l0s hideout but they are gone, along with their data. They must have left in a rush because we were  able to recover this file. What can you tell us about it?
"""
tags = ["Forensics", "Hardware", "Misc"]
flag = "clubeh{c0mpu73r_num3r1c41_c0n7r01_4fmC5sJz}"

[[hints]]
content = "GCODE"
