# Metadata for the CTF challenge repository

# Define CTFd URL
url = "https://ctf-2023.clubeh.ca"

# Define challenge categories
categories = [
	"web",
	"crypto",
	"forensics",
	"osint",
	"misc",
	"reverse",
]

# Define scoring parameters (based on challenge difficulty)
[scoring]
expected_player_count = 30

[scoring.initial]  # initial point value
easy	= 250
medium	= 250
hard	= 250

[scoring.final]  # lowest possible point value; when solves >= decay
easy	= 50
medium	= 50
hard	= 50

[scoring.decay]  # controls rate of decay. these are multiplied by scoring.expected_player_count.
easy	= 1.0
medium	= 1.0
hard	= 1.0
