[meta]
id = "jasons-website"
category = "web"
difficulty = "medium"
name = "Jason's New Website"
description = """
> by Arshdeep

Hi! I'm Jason, and I've recently made my very own website using Go!

Unfortunately, the t3l0s hackers have managed to get access to my data.  
I don't know how it happened - I even used JWTs for security!

Can you help me determine how they got in?

Link: [http://challenges.ctf-2023.clubeh.ca:61214/](http://challenges.ctf-2023.clubeh.ca:61214/)
"""
tags = ["Web Exploitation", "JWT", "Go"]
flag = "clubeh{1_4h0ugh4_jw45_w3r3_mag1c_2b7887ce}"

[static]
include = ["dynamic"]
exclude = ["dynamic/flag.txt"]
rm_prefixes = ["dynamic/"]
