[meta]
id = "botanic-market-1"
category = "misc"
difficulty = "medium"
name = "Botanic Market 1"
description = """
## Challenge Description (written in Markdown)

> by Spaghetti

This domain has been up for some time, but our systems continue to rank its reputation as very risky. Can you test the website's legitimacy?

No automated or bruteforcing tools are allowed or required for this challenge.
"""
tags = ["Artificial Intelligence"]
flag = "clubeh{b4ckd00r_vuLn3r481li7y_t9zDQ85O}"

[[hints]]
content = "Enumerate the website first."
