[meta]
id = "bussin"
category = "crypto"
difficulty = "medium"
name = "Bussin"
description = """
> by Spaghetti

Can you decode this cipher? Our forensics team is unable to figure out the encryption, but they did recover the phrase `pegasus` from the rest of the data recovered from t3l0s, that might be helpful.

`223361122152{32355346_1265_16_261461162465_4652254252365266}`

Flag format is all uppercase.
"""
tags = ["Cryptography"]
flags = [
	"clubeh{D0N7_B3_4_5QU4R3_7HZFH6H9}",
	"CLUBEH{D0N7_B3_4_5QU4R3_7HZFH6H9}",
]

[[hints]]
content = "Very old two dimensional cryptography algorithm."
