[meta]
id = "asimovs-second-law"
category = "web"
difficulty = "easy"
name = "Asimov's Second Law"
description = """
> by sudoBash418

Our playtesters said this challenge is so easy, even Googlebot could solve it.

So I made some tweaks to ensure Googlebot doesn't stand a chance.

Link: [http://challenges.ctf-2023.clubeh.ca:49486/](http://challenges.ctf-2023.clubeh.ca:49486/)
"""
tags = ["Web"]
flag = "clubeh{h1d1ng_fr0m_4h3_r0b045_7d37c0ec}"


[[hints]]
content = "What part of a website does Googlebot visit first?"
