[meta]
id = "botanic-market-0"
category = "web"
difficulty = "easy"
name = "Botanic Market 0"
description = """
> by Spaghetti

This website is still under development and we think that it may be a front for t3l0s, see what you can find.
"""
tags = ["Web"]
flag = "clubeh{c00k13_4u7h3n71c4710n_15_n07_54f3_eEr328VD}"

[[hints]]
content = "Inspector"
