[meta]
id = "botanic-market-0"
category = "web"
difficulty = "easy"
name = "Botanic Market 0"
description = """
> by Spaghetti

Our sources of intelligence tell us that this website is a front for t3l0s. It looks like they have deployed a development version to the live internet! See if you can take advantage of any vulnerabilities that you may find. 
"""
tags = ["Web"]
flag = "clubeh{c00k13_4u7h3n71c4710n_15_n07_54f3_eEr328VD}"
