# Containers used for this application
services:
  # Apache/PHP service
  apache-php:
    container_name: apache-php
    build: .
    ports: 
      - "80:80"
    networks:
      - olympians-network

  # MySQL service
  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=QTzp47dI5GoNqPzl
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes: 
      - ./static/olympians.sql:/docker-entrypoint-initdb.d/olympins.sql 
    networks:
      - olympians-network  
         
# Docker networks
networks:
  olympians-network:
    driver: bridge
