[meta]
id = "pillowcode"
category = "forensics"
difficulty = "medium"
name = "Pillowcode"
description = """
> by sudoBash418

We've managed to capture some data from an adversary - but they seem to have encoded the data in an image?
"""
tags = ["Forensics"]
flag = "clubeh{f1ddl1n9_w1th_p1x3l5_4nd_b1t5_118e08f9}"

[static]
include = [
	# pyproject.toml intentionally excluded
	"source/generate.py",
]
rm_prefixes = ["source/"]
