[meta]
id = "the-search-for-euros"
category = "osint"
difficulty = "hard"
name = "The Search for Euros"
description = """
> by Artemis

We want to get more information on Euros, who has a social media account with the username `57h3n0_3ury4l3_m3du54`.

We tried all the regular social media sites, but can't seem to find this user.  
Find the social media account and you'll find the flag.
"""
tags = ["Open Source Intelligence", "Social Media"]
flag = "clubeh{G0r9on_$1S73r5_4_L1f3_63572}"
