[meta]
id = "blinkenlights-1"
category = "misc"
difficulty = "medium"
name = "Blinkenlights 1"
description = """
> by Artemis

Here is another one of the microcontrollers used by t3l0s to send secret messages.

This pattern is different. Could you help me decode it?

Flag format: `clubeh{<recovered_text>}`
"""
tags = ["Hardware", "Forensics"]
# Morse code doesn't specify case, so we'll accept both versions
flags = [
	"clubeh{n3wtr1ck5325196}",
	"clubeh{N3WTR1CK5325196}",
]
