[package]
name = "libverify"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
name = "verify"
path = "src/lib.rs"

[profile.release]
lto = true
opt-level = "s"  # optimize for size (slightly better obfuscation)
