[meta]
id = "poc-or-gtfo"
category = "misc"
difficulty = "easy"
name = "PoC || GTFO"
description = """
> by Spaghetti

There is a flag hidden within this PDF newsletter, can you find it?
"""
tags = ["Misc"]
flag = "clubeh{d4t4_f131d5_dump_g8fas6}"

[[hints]]
content = "PDF objects and artifacts"
