[meta]
id = "monsters-den"
category = "web"
difficulty = "easy"
name = "Monsters Den"
description = """
> by Artemis

We found one of 4yph0n's old websites still online - maybe these pages have some information we could use to track them down?
"""
tags = ["Web"]
flag = "clubeh{3ch1dn@_A6E2C145}"


[dynamic.webserver]
build = "Containerfile"
ports = { web = 1337 }
