[meta]
id = "hashcap-1"
category = "crypto"
difficulty = "medium"
name = "hashcap-1"
description = """
> by tetratarius

We have managed to extract another password hash that we think is associated with one of the t3l0s hacker's accounts. Can you crack this hash?

Hash: `2790e01b73f4db3dbf3613fbe084d2a2de9d1d4d7ce24d8c8d5f47262f2b7ba7`

Flag format: `clubeh{<cracked_password>}`
"""
tags = ["Cryptography"]
flag = "clubeh{caesar441999}"


[[hints]]
content = "Look up how to crack password hashes... maybe advanced password cracking..."
