# This is an example challenge definition, written in TOML 1.0 (https://toml.io).
# All fields are required unless stated otherwise.

[meta]
# A unique, mostly-internal ID for this challenge.
# Must match the name of the challenge directory (where this file is).
id = "secretman"
# The ID of the user-facing category this challenge should be grouped under.
# Must match an existing entry in `../categories.toml`.
category = "reverse"
# The rated difficulty of the challenge (shown to the player as a title-cased tag).
# Must be one of "easy", "medium", "hard".
difficulty = "medium"
# The user-facing display name of the challenge.
name = "secretman"
# The user-facing description of the challenge.
# Supports Markdown + Jinja2.
description = """
> by tetratarius

We've found what we suspect to be one of the hacker's programs for storing secrets, we believe that a secret key is hidden within the program.
"""
# (optional) A list of tags for the challenge, as displayed by CTFd.
# Note that the difficulty always shows up as the first tag, regardless of tags defined here.
tags = ["Reversing"]


[scoring]
# The flag that the user must submit to prove they've solved the challenge.
flag = "clubeh{tH3s3us_sUcK50rz}"


[[hints]]
content = "look up what a .pyc file is"

[[hints]]
content = "look up how to reverse engineer a .pyc file"
